// Generates lib/api-types.ts from ../contract/schema.json (whose root is empty; the models live in $defs).
import { readFileSync, writeFileSync } from "node:fs";
import { compile } from "json-schema-to-typescript";

const schema = JSON.parse(readFileSync(new URL("../../contract/schema.json", import.meta.url), "utf8"));
const wrapper = {
  title: "AtelierContract",
  type: "object",
  additionalProperties: false,
  $defs: schema.$defs,
  properties: Object.fromEntries(Object.keys(schema.$defs).map((k) => [k, { $ref: `#/$defs/${k}` }])),
};
const ts = await compile(wrapper, "AtelierContract", { additionalProperties: false, bannerComment: "/* eslint-disable */\n// Generated by scripts/gen-types.mjs from contract/schema.json. Do not edit by hand." });
writeFileSync(new URL("../lib/api-types.ts", import.meta.url), ts);
