/* eslint-disable */
// Generated by scripts/gen-types.mjs from contract/schema.json. Do not edit by hand.

/**
 * Which swipe list an item lands in and how outfit assembly treats it.
 */
export type Category = "tops" | "bottoms" | "jackets";
/**
 * Which pose region vision segments. A dress is category tops, garment_type dress.
 */
export type GarmentType = "shirt" | "dress" | "pants" | "skirt" | "shorts" | "jacket" | "coat";
export type Color = string | null;
export type ItemName = string | null;
export type TempHandle = string;
/**
 * @minItems 3
 * @maxItems 3
 */
export type Candidates = [Candidate, Candidate, Candidate];
export type Index = number;
/**
 * V-S3: the three analyze candidates, in index order 0, 1, 2.
 */
export type CandidateVariant = "tight" | "balanced" | "generous";
export type CutoutUrl = string;
/**
 * @minItems 3
 * @maxItems 3
 */
export type Lab = [unknown, unknown, unknown];
/**
 * @minItems 3
 * @maxItems 3
 */
export type Lch = [unknown, unknown, unknown];
export type Hex = string;
export type Name = string;
export type Family = string;
export type IsNeutral = boolean;
export type EverydayNeutral = boolean;
export type DisplayName = string | null;
export type AvatarId = string;
export type WireframeUrl = string;
export type AvatarUrl = string;
export type CreatedAt = string;
export type AvatarId1 = string;
export type WireframeUrl1 = string;
export type AvatarUrl1 = string;
export type ErrorCode =
  | "invalid_request"
  | "not_found"
  | "pose_rejected"
  | "no_person_detected"
  | "unsupported_image"
  | "analyze_failed"
  | "handle_expired"
  | "gemini_unavailable"
  | "not_implemented"
  | "internal_error";
export type Message = string;
export type Family1 = string;
export type Count = number;
export type Share = number;
export type Hex1 = string;
export type Status = "ok";
export type Db = "ok";
export type Id = string;
export type CutoutUrl1 = string;
export type RetailerColor = string | null;
export type RetailerItemName = string | null;
export type CreatedAt1 = string;
export type Items = Item[];
export type OutfitId = string;
/**
 * S-S2 outfit strategies, in degradation-ladder order.
 */
export type Strategy =
  "neutral_anchor" | "everyday_neutral_base" | "analogous" | "complementary" | "monochrome_highlight" | "sandwich";
export type TopId = string;
export type BottomId = string;
export type JacketId = string | null;
export type Explanation = string;
export type Score = number;
/**
 * 2.5.0: optional preset for POST /outfits/generate (never free text).
 */
export type OutfitStyle = "casual" | "going_out" | "business" | "monochrome";
export type Limit = number;
/**
 * @maxItems 5
 */
export type Outfits =
  | []
  | [Outfit]
  | [Outfit, Outfit]
  | [Outfit, Outfit, Outfit]
  | [Outfit, Outfit, Outfit, Outfit]
  | [Outfit, Outfit, Outfit, Outfit, Outfit];
export type ItemCount = number;
export type NeutralShare = number;
export type Families = FamilyShare[];
export type ItemId = string;
export type Hex2 = string;
export type DisplayName1 = string | null;
export type Family2 = string;
export type Swatches = PaletteSwatch[];
export type MissingFamilies = string[];
/**
 * @maxItems 6
 */
export type Insights =
  | []
  | [string]
  | [string, string]
  | [string, string, string]
  | [string, string, string, string]
  | [string, string, string, string, string]
  | [string, string, string, string, string, string];
/**
 * @maxItems 3
 */
export type MostVersatile =
  [] | [VersatileItem] | [VersatileItem, VersatileItem] | [VersatileItem, VersatileItem, VersatileItem];
export type ItemId1 = string;
export type OutfitCount = number;
export type TempHandle1 = string;
export type Ok = true;
export type Name1 = string | null;
export type Attributes1 = {
  [k: string]: string;
} | null;
export type RenderId = string;
export type RenderStatus = "pending" | "done" | "failed";
export type LocalUrl = string;
export type GeneratedUrl = string | null;
export type AvatarId2 = string;
export type TopId1 = string;
export type BottomId1 = string;
export type JacketId1 = string | null;
export type TempHandle2 = string;
export type CandidateIndex = number;

export interface AtelierContract {
  AnalyzeForm?: AnalyzeForm;
  AnalyzeResponse?: AnalyzeResponse;
  Avatar?: Avatar;
  AvatarScanResponse?: AvatarScanResponse;
  Candidate?: Candidate;
  CandidateVariant?: CandidateVariant;
  Category?: Category;
  ErrorBody?: ErrorBody;
  ErrorCode?: ErrorCode;
  ErrorResponse?: ErrorResponse;
  ExtractedColor?: ExtractedColor;
  FamilyShare?: FamilyShare;
  GarmentType?: GarmentType;
  HealthResponse?: HealthResponse;
  Item?: Item;
  ItemListResponse?: ItemListResponse;
  Outfit?: Outfit;
  OutfitStyle?: OutfitStyle;
  OutfitsGenerateRequest?: OutfitsGenerateRequest;
  OutfitsGenerateResponse?: OutfitsGenerateResponse;
  PaletteInsights?: PaletteInsights;
  PaletteSwatch?: PaletteSwatch;
  RejectRequest?: RejectRequest;
  RejectResponse?: RejectResponse;
  RenameRequest?: RenameRequest;
  RenderJob?: RenderJob;
  RenderRequest?: RenderRequest;
  RenderStatus?: RenderStatus;
  SaveRequest?: SaveRequest;
  Strategy?: Strategy;
  VersatileItem?: VersatileItem;
}
/**
 * Form fields of POST /items/analyze (multipart), besides the `image` file part.
 *
 * Not a JSON body; published so the backend can validate the form and the frontend can
 * type it. An invalid category/garment_type pair is a 400 invalid_request.
 */
export interface AnalyzeForm {
  category: Category;
  garment_type: GarmentType;
  color?: Color;
  item_name?: ItemName;
}
/**
 * POST /items/analyze. Persists nothing; exactly three candidates, index 0..2 in order.
 */
export interface AnalyzeResponse {
  temp_handle: TempHandle;
  candidates: Candidates;
}
export interface Candidate {
  index: Index;
  variant: CandidateVariant;
  cutout_url: CutoutUrl;
  primary_color: ExtractedColor;
  secondary_color?: ExtractedColor | null;
}
/**
 * One extracted color (V-C1..V-C5). Numeric values are the truth; names are a lookup.
 */
export interface ExtractedColor {
  lab: Lab;
  lch: Lch;
  hex: Hex;
  name: Name;
  family: Family;
  is_neutral: IsNeutral;
  everyday_neutral: EverydayNeutral;
  display_name?: DisplayName;
}
/**
 * GET /avatar/{avatar_id}
 */
export interface Avatar {
  avatar_id: AvatarId;
  wireframe_url: WireframeUrl;
  avatar_url: AvatarUrl;
  created_at: CreatedAt;
}
/**
 * POST /avatar/scan (multipart: image). A pose failure is 422 pose_rejected with an actionable message.
 */
export interface AvatarScanResponse {
  avatar_id: AvatarId1;
  wireframe_url: WireframeUrl1;
  avatar_url: AvatarUrl1;
}
export interface ErrorBody {
  code: ErrorCode;
  message: Message;
}
/**
 * Every 4xx/5xx response body.
 */
export interface ErrorResponse {
  error: ErrorBody;
}
/**
 * One colors.json family's presence in the closet, by item primary color.
 */
export interface FamilyShare {
  family: Family1;
  count: Count;
  share: Share;
  hex: Hex1;
}
export interface HealthResponse {
  status: Status;
  db: Db;
}
/**
 * A saved closet item. GET /items/{slug}, POST /items/save, and each entry of GET /items.
 */
export interface Item {
  id: Id;
  category: Category;
  garment_type: GarmentType;
  cutout_url: CutoutUrl1;
  primary_color: ExtractedColor;
  secondary_color?: ExtractedColor | null;
  retailer_color?: RetailerColor;
  retailer_item_name?: RetailerItemName;
  attributes?: Attributes;
  created_at: CreatedAt1;
}
export interface Attributes {
  [k: string]: unknown;
}
/**
 * GET /items?category=tops|bottoms|jackets. Stable order: created_at, newest first.
 */
export interface ItemListResponse {
  items: Items;
}
/**
 * bottom + (top or dress) + optional jacket (S-O1..S-O3).
 */
export interface Outfit {
  outfit_id: OutfitId;
  strategy: Strategy;
  top_id: TopId;
  bottom_id: BottomId;
  jacket_id?: JacketId;
  explanation: Explanation;
  score: Score;
}
/**
 * POST /outfits/generate. The body may be {} (limit defaults to 5). 2.5.0 (additive): optional
 * `style` preset; omitted or null means the usual random pick among the best outfits.
 */
export interface OutfitsGenerateRequest {
  limit?: Limit;
  style?: OutfitStyle | null;
}
/**
 * Up to 5 outfits, best first. Fewer (or none, for an unsatisfiable closet) is normal.
 */
export interface OutfitsGenerateResponse {
  outfits: Outfits;
}
/**
 * GET /insights/palette: closet-wide color summary for the palette page (styling lane).
 */
export interface PaletteInsights {
  item_count: ItemCount;
  neutral_share: NeutralShare;
  families: Families;
  swatches: Swatches;
  missing_families: MissingFamilies;
  insights: Insights;
  most_versatile: MostVersatile;
}
export interface PaletteSwatch {
  item_id: ItemId;
  category: Category;
  hex: Hex2;
  display_name?: DisplayName1;
  family: Family2;
}
export interface VersatileItem {
  item_id: ItemId1;
  outfit_count: OutfitCount;
}
/**
 * POST /items/reject. Nothing persists; the rejection is logged.
 */
export interface RejectRequest {
  temp_handle: TempHandle1;
}
export interface RejectResponse {
  ok: Ok;
}
/**
 * PATCH /items/{slug}. Edits a saved item: its display name (retailer_item_name) and/or its
 * free-form details (attributes). 2.3.0 added `name`; 2.4.0 (additive) made it optional and added
 * `attributes`: merged into the stored map, any value is allowed (unknown words are fine), and an
 * empty string removes that key. The id and all other stored data never change.
 */
export interface RenameRequest {
  name?: Name1;
  attributes?: Attributes1;
}
/**
 * POST /render and GET /render/{render_id}. local_url is always present and correct;
 * generated_url is set exactly when status is done.
 */
export interface RenderJob {
  render_id: RenderId;
  status: RenderStatus;
  local_url: LocalUrl;
  generated_url?: GeneratedUrl;
}
/**
 * POST /render
 */
export interface RenderRequest {
  avatar_id: AvatarId2;
  top_id: TopId1;
  bottom_id: BottomId1;
  jacket_id?: JacketId1;
}
/**
 * POST /items/save. category/garment_type/retailer fields were captured at analyze.
 */
export interface SaveRequest {
  temp_handle: TempHandle2;
  candidate_index: CandidateIndex;
}
